name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        jdk: [21]

    steps:
      - uses:  actions/checkout@v4

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and test
        run: ./gradlew check koverXmlReport --no-daemon

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: build/reports/kover/report.xml
          fail_ci_if_error: false
